#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N myjob_lab24
#PBS -o myjob_lab24.out
#PBS -e myjob_lab24.err
#PBS -q workq
#PBS -A loni_cyen405
#PBS -m e
#PBS -M ksg027@latech.edu
work="/home/kgusti/lab2"
XFILE="lab24"
cd $work

echo "MPI run with 4 processes."
mpirun -np 4 -machinefile $PBS_NODEFILE ./$XFILE
echo "MPI run with 8 processes."
mpirun -np 8 -machinefile $PBS_NODEFILE ./$XFILE
